crossroad/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # 默认首页
	url(r'^$', views.IndexView.as_view(), name='index'),
	# 对应分类首页
	url(r'^category/(?P<category>\w+)/$', views.IndexView.as_view(), name='category'),
	# 标签列表页
	url(r'^tags/(?P<tags>.+)/$', views.IndexView.as_view(), name='tags'),
	# 文章内容详情
	url(r'^blog/(?P<alias>[\w-]+)/(?P<slug>[\w]+)/$', views.BlogDetailView.as_view(), {'order_by':'pub_date'}, name='blog_detail'),
]

crossroad/crossroad/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

crossroad/blog/models.py
# coding:utf-8

import hashlib

from django.db import models
from django.contrib.auth.models import User

SLUGKEY = 'crossroad'
# 文章标签 与 博客多对多关系
class BlogTags(models.Model):
    # 标签
    btag = models.CharField(max_length=31)
    # 别名 用于url
    alias = models.SlugField()

    def __str__(self):
        return self.btag

# 文章分类
class BlogCategory(models.Model):
    # 分类
    bcategory = models.CharField(max_length=31)
    # 别名 用于url
    alias = models.SlugField()
    def __str__(self):
        return self.bcategory

# 文章正文
class Blog(models.Model):

    # 文章标题
    title = models.CharField(max_length=100)
    # 文章概要
    summary = models.CharField(max_length=200)
    # 文章正文
    content = models.TextField()
    # 发表时间
    pub_date = models.DateTimeField()
    # 文章url识别字符串，一串md5值
    slug = models.SlugField(blank=True, null=True)
    # 文章标签
    blogtag = models.ManyToManyField(BlogTags)
    # 文章分类
    blogcategory = models.ForeignKey(BlogCategory)

    def save(self, *args, **kwargs):
        # 生成slug值
        md5 = hashlib.md5()
        md5.update(str(self.id).encode('utf-8'))
        md5.update(SLUGKEY.encode('utf-8'))
        self.slug = md5.hexdigest()
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

crossroad/blog/views.py
from django.views import generic

from .models import Blog
from .filters import search,blog_filter


class IndexView(generic.ListView):
    model = Blog                          #显示内容的模板类
    template_name = 'blog/index.html'    #前端html模板
    paginate_by = 5                        #每页条目数
    paginate_orphans = 1                #最大孤页显示条目数

    #以下为非继承的类属性
    #设置全文检索的查找范围
    search_fields = ['title','summary']
    searched = False    #判断是否经过查询
    btype_num_list = None    #对筛选结果计数后组成的一个，BlogType分类的list，作为上下文发送给前端
    btype_uri = ''    #将进行分类查询的字符串，作为上下文发送给前端，以便前端组成url

    # 处理queryset对象
    def get_queryset(self):
        category = self.kwargs.get('category')
        tags = self.kwargs.get('tags')
        querysets = None
        # 判断url是否来自category
        if category:
            querysets = Blog.objects.filter(blogcategory__alias=category)
        elif tags:
            querysets = Blog.objects.filter(blogtag__alias=tags)
        else:
            querysets = Blog.objects.all()

        # 处理搜索框的搜索字符串， 返回查询的结果，没有则返回原始传入的数据querysets
        query_results, self.searched = search(self.request, querysets, self.search_fields)

        # 获取标签筛选的字符串，没有则为‘’
        tags_string = self.request.GET.get('tag') or ''
        tags_list = set(tags_string.split(','))
        self.btags_uri = ','.join(tags_list)    #赋给类属性

        # 对query_results进行标签类型的筛选
        queryset_list, self.btags_num_list = blog_filter(query_results, tags_list)
        return queryset_list.order_by('-pub_date')

    # 处理返回的上下文
    def get_context_data(self, **kwargs):
        #获取为处理过的上下文数据
        context = super(IndexView,self).get_context_data(**kwargs)

        #以下均为新增的上下文，以便在前端进行布局，设置超链接url等
        if self.searched:
            results_num = context['paginator'].count
            # 文章数量
            context['results_num'] = results_num
            # 查询字符串
            context['form_string'] = self.request.GET.get('q','')
        # 标签列表数据
        context['btags_num_list'] = self.btags_num_list
        # 本次请求标签的内容
        context['btags_uri'] = self.btags_uri
        context['abs_url'] = self.request.get_raw_uri().split('?')[0]
        return context

# 文章内容视图
class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    search_fields = ['title','content']
    searched = False

    #重写父类get_context_data方法
    def get_context_data(self,**kwargs):
        #获取为处理过的上下文数据
        order_by = self.kwargs.get('order_by')
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        #以下均为新增的上下文，以便在前端进行布局，设置超链接url等
        alias = self.kwargs.get('alias')
        query_results,self.searched = search(self.request,Blog.objects.filter(blogcategory__alias=alias), \
                                             self.search_fields)
        querysets = query_results.order_by(order_by)
        if self.searched:
            results_num = querysets.count()
            context['results_num'] = results_num
            context['form_string'] = self.request.GET.get('q','')
        context['object_list'] = querysets
        context['abs_url'] = self.request.get_raw_uri().split('?')[0]
        return context

crossroad/blog/templates/blog/_blog.html
            {% load custom_markdown %}
            {% if object %}
            <div class="blog-post">
              <h3 class="blog-post-title">{{object.title}}</h3>
              <p class="blog-post-meta">{{object.pub_date}}
                  <em class="tag">   |   分类：
                      <a href="{% url 'blog:category' category=blog.blogcategory.alias %}">{{object.blogcategory.bcategory}}</a>
                  </em>
                <cite class='tag fr'>
                    标签：
                  {% for tag in object.blogtag.all %}
                    <span class="badge"><a href="{% url 'blog:tags' tags=tag.alias  %}">{{tag.btag}}</a></span>
                  {% endfor %}
                </cite>
              </p>
              <hr>
              <p>{{object.content|custom_markdown}}</p>
            </div><!-- /.blog-post -->
            {% endif %}

crossroad/blog/templates/blog/_duoshuo.html
            <!-- 多说评论框 start -->
  <div class="ds-thread" data-thread-key="{{blog.id}}" data-title="{{blog.title}}" data-url="{{request.built_abslout_uri}}"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"francisrol"};
  (function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.unstable.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] 
     || document.getElementsByTagName('body')[0]).appendChild(ds);
  })();
  </script>
<!-- 多说公共JS代码 end -->

crossroad/blog/templates/blog/_summary.html
            {% load custom_markdown %}
            {% for blog in object_list %}
            <div class="blog-post">
              <h2 class="blog-post-title"><a href="{% url 'blog:blog_detail' alias=blog.blogcategory.alias slug=blog.slug %}">{{blog.title}}</a></h2>
                <p>{{blog.summary|custom_markdown}}
                <a class='btn btn-primary btn-xs clearfix' href="{% url 'blog:blog_detail' alias=blog.blogcategory.alias slug=blog.slug %}">查看更多>></a>
                </p>
              <p class="blog-post-meta">{{blog.pub_date}}
                  <em class="tag">   |   分类：
                      <a href="{% url 'blog:category' category=blog.blogcategory.alias %}">{{blog.blogcategory.bcategory}}</a>
                  </em>
                <cite class='tag fr'>
                    标签：
                  {% for tag in blog.blogtag.all %}
                    <span class="badge"><a href="{% url 'blog:tags' tags=tag.alias %}">{{tag.btag}}</a></span>
                  {% endfor %}                  
                </cite>
              </p>
            </div><!-- /.blog-post -->
            <hr>
            {% endfor %}

crossroad/blog/templates/blog/base.html
<!DOCTYPE html>
{% load i18n static %}
<html lang="{{ LANGUAGE_CODE|default:'zh-cn' }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'blog/image/logo.jpg' %}">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'blog/css/reset.css' %}" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles fo this template -->
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/highlight.css' %}" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

</head>

<body class="{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now 'Z' %}">
  <!-- Nav -->
  {% block nav-global %}
  <div class="container blog-nav">
      <nav class="navbar navbar-default blog-masthead">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">切换导航</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">CrossRoad</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="blog-nav nav navbar-nav">
          <li><a id='nav-ne' class="blog-nav-item" href="{% url 'blog:index' %}">最新文章</a></li>
          <li><a id='nav-py' class="blog-nav-item" href="">ABOUT</a></li>
        </ul>
      </div>
    </nav>
  </div>
  {% endblock %}
  <!-- END Nav -->

  <!-- Container -->
  <div class="container">
    <!-- Content -->
      {% block content %}
        {% block sidebar %}{% endblock %}
      {% endblock %}
    <!-- END Content -->
    
    {% block scripts %}
        <!-- core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="//cdn.bootcss.com/crypto-js/3.1.2/components/core-min.js"></script>
      <script src="//cdn.bootcss.com/crypto-js/3.1.2/components/sha1.js"></script>
      <script src="{% static 'blog/js/blog.js' %}"></script>
      <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% endblock %}
  </div>
  <!-- END Container -->

  <!-- Footer -->
  {% block footer %}
    <footer class="blog-footer">
    <div>Powered by<a target='_blank' href="http://docs.djangoproject.com"> Django</a> and<a target='_blank' href="http://www.bootcss.com/"> Bootstrap</a></div>
        <p>@Copyright 2017</p>
    </footer>
  {% endblock %}
  <!-- END Footer -->  
</body>
</html>

crossroad/blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
      <div class="row">
              <!-- Sidebar -->
       
        <!-- Blog-main -->
        <div class="col-sm-9  blog-main">
          <div class='blog-include'>
           {% include 'blog/_blog.html' %}
          </div>
          {% include 'blog/_duoshuo.html' %}
        </div><!-- End blog-main -->

 				{% block sidebar %}
        <div class="col-sm-3 blog-sidebar">
        <div class="sidebar-module">
        	<h4>搜索获取更多...</h4>
          <form class='search' method='GET'>
            <div class="input-group">
              <input type="text" class="form-control" name='q' placeholder="Search for..." autofocus {% if form_string %}value='{{form_string}}'{% endif %}>
              <span class="input-group-btn">
                <button class="search-btn btn btn-default" type="submit">搜索</button>
              </span>
            </div><!-- /input-group -->
          </form>

         {% if form_string %}
          <p class='loading'><img src="{% static 'blog/image/loading.gif' %}" alt=""> 正在搜索</p>
          <p class="search-bar">共搜索到<span class="badge">{{results_num}}</span>条结果，返回<a href="{% url 'blog:index' %}"> 查看全部</a>。</p>
          {% endif %}
          </div>
            <div class="sidebar-module sidebar">
            <h4>相关文章</h4>
            <ul class="nav nav-sidebar">
              {% for blog in object_list %}
                <li><a href="{% url 'blog:blog_detail' alias=blog.blogcategory.alias slug=blog.slug %}">{{blog.title}}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
          </div>

<!-- End sidebar -->
        {% endblock %}

      </div><!-- End row -->
{% endblock %}

crossroad/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} Home--Francis Web {% endblock %}

      {% block content %}

      <!--{% block pagetitle %}-->
        <!--<div class="blog-header">-->
          <!--<h1 class="blog-title">CrossRoad</h1>-->
          <!--<p class="lead blog-description">&#45;&#45;&#45;&#45;Francis的个人小站</p>-->
        <!--</div>-->
      <!--{% endblock %}-->

      <div class="row">
        <!-- Blog-main -->
        <div class="col-sm-9 blog-main">


          <hr>
          <div class='blog-include'>
           {% include 'blog/_summary.html' %}
          <nav>
            <ul class="pagination">
              <li {% if not page_obj.has_previous %}class='disabled'>
                <a {% else%}><a href="{{abs_url}}?{% if form_string %}q={{form_string}}&{% endif %}{% if btags_uri %}tag={{btags_uri}}&{% endif %}page={{page_obj.number|add:-1}}" {% endif %} aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
                </li>
                  {% for pn in paginator.page_range %}
                  <li {% if pn == page_obj.number %}class='active'><a {% else %}><a href="{{abs_url}}?{% if form_string %}q={{form_string}}&{% endif %}{% if btags_uri %}tag={{btags_uri}}&{% endif %}page={{pn}}"{% endif %}>{{pn}}</a></li>
                  {% endfor %}
                <li {% if not page_obj.has_next %}class='disabled'>
                <a {% else%}><a href="{{abs_url}}?{% if form_string %}q={{form_string}}&{% endif %}{% if btags_uri %}tag={{btags_uri}}&{% endif %}page={{page_obj.number|add:1}}" {% endif %} aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
          </div>
        </div><!-- End blog-main -->

        <!-- Sidebar -->
        {% block sidebar %}
       
        <div class="col-sm-3 blog-sidebar">
          <form class='search' method='GET'>
            <div class="input-group">
              <input type="text" class="form-control" name='q' placeholder="Search for..." autofocus {% if form_string %}value='{{form_string}}'{% endif %}>
              <span class="input-group-btn">
                <button class="search-btn btn btn-default" type="submit">搜索</button>
              </span>
            </div><!-- /input-group -->
          </form>
          {% if form_string %}
          <p class='loading'><img src="{% static 'blog/image/loading.gif' %}" alt=""> 正在搜索</p>
          <p class="search-bar">共搜索到<span class="badge">{{results_num}}</span>条结果，返回<a href="{% url 'blog:index' %}"> 查看全部</a>。</p>
          {% endif %}
          <div class="sidebar-module">
            <h4>标签目录</h4>
            <ol class="list-unstyled">
              {% for tag_alias,tag_name,nums in btags_num_list %}
                {% if tag_name %}
                <li><a href="{{abs_url}}?{% if form_string %}q={{form_string}}&{% endif %}tag={% if tag_name not in btags_uri %}{{btags_uri}},{{tag_name}}{% else %}{{btags_uri}}{% endif %}" class='btn btn-primary btn-xs'>{{tag_alias}}<span class="badge">{{nums}}</span></a>
                {% endif %}
                </li>
              {% endfor %}
            </ol>
          </div>
        </div><!-- End sidebar -->
        {% endblock %}
      </div><!-- End row -->
      {% endblock %}